/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/0GKz6dTrJYd
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Yeseva_One } from 'next/font/google'

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Select } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function home() {
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <header className="bg-gray-900 text-white py-4 px-6 md:px-12">
        <div className="container mx-auto flex items-center justify-between">
          <Link className="text-2xl font-bold" href="#">
            Official Document Translation
          </Link>
          <nav className="hidden md:flex items-center space-x-6">
            <Link className="hover:underline" href="#">
              Home
            </Link>
            <Link className="hover:underline" href="#">
              Services
            </Link>
            <Link className="hover:underline" href="#">
              Contact
            </Link>
          </nav>
          <button className="md:hidden">
            <MenuIcon className="h-6 w-6" />
          </button>
        </div>
      </header>
      <main className="flex-1">
        <section className="bg-gray-100 py-12 md:py-20">
          <div className="container mx-auto px-6 md:px-12">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div>
                <h1 className="text-3xl md:text-4xl font-bold mb-4">Trusted Translation Services</h1>
                <p className="text-gray-700 leading-relaxed mb-6">
                  Our team of professional translators provides accurate and reliable translations of official
                  documents, including passports, birth certificates, university degrees, and more. Trust us with your
                  important documents.
                </p>
                <Link
                  className="inline-flex items-center px-4 py-2 bg-gray-900 text-white rounded-md hover:bg-gray-800"
                  href="#">
                  Get a Quote
                  <ArrowRightIcon className="ml-2 h-5 w-5" />
                </Link>
              </div>
              <div>
                <img
                  alt="Translation Services"
                  className="rounded-md"
                  height={400}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "500/400",
                    objectFit: "cover",
                  }}
                  width={500} />
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-20" id="services">
          <div className="container mx-auto px-6 md:px-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-8">Our Services</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              <div className="bg-white rounded-md shadow-md p-6">
                <StampIcon className="h-12 w-12 mb-4" />
                <h3 className="text-xl font-bold mb-2">Passport Translation</h3>
                <p className="text-gray-700 leading-relaxed">
                  We provide accurate translations of passports for official purposes.
                </p>
              </div>
              <div className="bg-white rounded-md shadow-md p-6">
                <BadgeIcon className="h-12 w-12 mb-4" />
                <h3 className="text-xl font-bold mb-2">Birth Certificate Translation</h3>
                <p className="text-gray-700 leading-relaxed">
                  Trust us with your birth certificate translations for legal and official use.
                </p>
              </div>
              <div className="bg-white rounded-md shadow-md p-6">
                <DiscIcon className="h-12 w-12 mb-4" />
                <h3 className="text-xl font-bold mb-2">Diploma Translation</h3>
                <p className="text-gray-700 leading-relaxed">
                  We can translate your university degrees and diplomas for academic and professional purposes.
                </p>
              </div>
              <div className="bg-white rounded-md shadow-md p-6">
                <FileQuestionIcon className="h-12 w-12 mb-4" />
                <h3 className="text-xl font-bold mb-2">Legal Document Translation</h3>
                <p className="text-gray-700 leading-relaxed">
                  Our team can handle the translation of various legal documents, such as contracts and agreements.
                </p>
              </div>
              <div className="bg-white rounded-md shadow-md p-6">
                <ReceiptIcon className="h-12 w-12 mb-4" />
                <h3 className="text-xl font-bold mb-2">Medical Record Translation</h3>
                <p className="text-gray-700 leading-relaxed">
                  Trust us with the translation of your medical records and documents.
                </p>
              </div>
              <div className="bg-white rounded-md shadow-md p-6">
                <DownloadIcon className="h-12 w-12 mb-4" />
                <h3 className="text-xl font-bold mb-2">Official Document Translation</h3>
                <p className="text-gray-700 leading-relaxed">
                  We can translate a wide range of official documents, such as government-issued IDs and certificates.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-gray-100 py-12 md:py-20" id="contact">
          <div className="container mx-auto px-6 md:px-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-8">Contact Us</h2>
            <form className="bg-white rounded-md shadow-md p-6 md:p-8">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <Label htmlFor="name">Name</Label>
                  <Input id="name" placeholder="Enter your name" type="text" />
                </div>
                <div>
                  <Label htmlFor="email">Email</Label>
                  <Input id="email" placeholder="Enter your email" type="email" />
                </div>
              </div>
              <div className="mb-6">
                <Label htmlFor="document">Document Type</Label>
                <Select id="document">
                  <option value="">Select document type</option>
                  <option value="passport">Passport</option>
                  <option value="birth-certificate">Birth Certificate</option>
                  <option value="diploma">Diploma</option>
                  <option value="legal-document">Legal Document</option>
                  <option value="medical-record">Medical Record</option>
                  <option value="other">Other</option>
                </Select>
              </div>
              <div className="mb-6">
                <Label htmlFor="message">Message</Label>
                <Textarea id="message" placeholder="Enter your message" />
              </div>
              <Button className="w-full" type="submit">
                Submit Request
              </Button>
            </form>
          </div>
        </section>
      </main>
      <footer className="bg-gray-900 text-white py-6 md:py-8">
        <div
          className="container mx-auto px-6 md:px-12 flex items-center justify-between">
          <p className="text-sm">© 2024 Official Document Translation. All rights reserved.</p>
          <nav className="hidden md:flex items-center space-x-6">
            <Link className="hover:underline" href="#">
              Privacy Policy
            </Link>
            <Link className="hover:underline" href="#">
              Terms of Service
            </Link>
          </nav>
        </div>
      </footer>
    </div>)
  );
}

function ArrowRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>)
  );
}


function BadgeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z" />
    </svg>)
  );
}


function DiscIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="2" />
    </svg>)
  );
}


function DownloadIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" x2="12" y1="15" y2="3" />
    </svg>)
  );
}


function FileQuestionIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M12 17h.01" />
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7z" />
      <path d="M9.1 9a3 3 0 0 1 5.82 1c0 2-3 3-3 3" />
    </svg>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function ReceiptIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M4 2v20l2-1 2 1 2-1 2 1 2-1 2 1 2-1 2 1V2l-2 1-2-1-2 1-2-1-2 1-2-1-2 1Z" />
      <path d="M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8" />
      <path d="M12 17.5v-11" />
    </svg>)
  );
}


function StampIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 22h14" />
      <path
        d="M19.27 13.73A2.5 2.5 0 0 0 17.5 13h-11A2.5 2.5 0 0 0 4 15.5V17a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-1.5c0-.66-.26-1.3-.73-1.77Z" />
      <path d="M14 13V8.5C14 7 15 7 15 5a3 3 0 0 0-3-3c-1.66 0-3 1-3 3s1 2 1 3.5V13" />
    </svg>)
  );
}
