/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Ap8Ui2u8gzy
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"

export function UserProfile() {
  return (
    (<div className="flex flex-col h-full">
      <header
        className="bg-gray-900 text-gray-50 py-6 px-4 md:px-6 dark:bg-gray-50 dark:text-gray-900">
        <div className="container flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Avatar>
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>CN</AvatarFallback>
            </Avatar>
            <div>
              <h1 className="text-2xl font-bold">Cody Newman</h1>
              <p className="text-sm text-gray-50/80 dark:text-gray-900/80">cody@example.com</p>
            </div>
          </div>
        </div>
      </header>
      <main className="flex-1 py-8 px-4 md:px-6">
        <div className="container grid gap-8 md:grid-cols-2 lg:grid-cols-3">
          <section className="space-y-6">
            <h2 className="text-xl font-bold">Información de Usuario</h2>
            <div className="space-y-4">
              <div className="grid gap-2">
                <Label htmlFor="name">Name</Label>
                <Input id="name" defaultValue="Cody Newman" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="email">Email</Label>
                <Input id="email" type="email" defaultValue="cody@example.com" />
              </div>
              <Button className="ml-auto">Save Changes</Button>
            </div>
          </section>
          <section className="space-y-6">
            <h2 className="text-xl font-bold">Change Password</h2>
            <div className="space-y-4">
              <div className="grid gap-2">
                <Label htmlFor="current-password">Current Password</Label>
                <Input id="current-password" type="password" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="new-password">New Password</Label>
                <Input id="new-password" type="password" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="confirm-password">Confirm Password</Label>
                <Input id="confirm-password" type="password" />
              </div>
              <Button className="ml-auto">Change Password</Button>
            </div>
          </section>
          <section className="space-y-6">
            <h2 className="text-xl font-bold">Projects</h2>
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-1">
              <Card className="p-4 space-y-2">
                <div className="flex items-center justify-between">
                  <h3 className="text-lg font-medium">Project A</h3>
                  <div
                    className="px-2 py-1 rounded-full bg-green-100 text-green-800 text-xs font-medium">Active</div>
                </div>
                <p className="text-gray-500 dark:text-gray-400">This is a description of Project A, which is currently active.</p>
              </Card>
              <Card className="p-4 space-y-2">
                <div className="flex items-center justify-between">
                  <h3 className="text-lg font-medium">Project B</h3>
                  <div
                    className="px-2 py-1 rounded-full bg-yellow-100 text-yellow-800 text-xs font-medium">
                    Pending
                  </div>
                </div>
                <p className="text-gray-500 dark:text-gray-400">This is a description of Project B, which is currently pending.</p>
              </Card>
              <Card className="p-4 space-y-2">
                <div className="flex items-center justify-between">
                  <h3 className="text-lg font-medium">Project C</h3>
                  <div
                    className="px-2 py-1 rounded-full bg-red-100 text-red-800 text-xs font-medium">Completed</div>
                </div>
                <p className="text-gray-500 dark:text-gray-400">
                  This is a description of Project C, which is currently completed.
                </p>
              </Card>
            </div>
          </section>
        </div>
      </main>
    </div>)
  );
}
